spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/new_JiaKao?serverTimezone=UTC

server:
  port: 8888


logging:
  level:
     com.mj.jk.mapper: debug





